const KEY='comissionaia_v1';
const safetyItems=['Área de trabalho organizada e delimitada','EPI adequado selecionado e inspecionado','EPC disponível e aplicável','Ausência de partes energizadas expostas','Procedimento de bloqueio e sinalização definido','Ferramentas inspecionadas e adequadas','Diagrama / ordem de serviço disponível','Riscos elétricos e ocupacionais identificados'];
const assemblyItems=['Infraestrutura e fixação inspecionadas','Condutores identificados e organizados','Circuito de potência conforme diagrama','Circuito de comando conforme diagrama','Aterramento / PE verificado','Aperto mecânico e elétrico conferido','Proteções ajustadas / dimensionadas conforme projeto','Teste de continuidade realizado'];
const commissionItems=['Inspeção visual concluída','Circuito de potência verificado','Circuito de comando verificado','Proteções verificadas','Aterramento verificado','Parametrização conferida','Teste a frio concluído','Teste energizado concluído','Medições registradas','Falhas corrigidas e retestadas'];
const evidenceItems=['Diagrama elétrico anexado/registrado','Checklist de segurança preenchido','Registro das medições concluído','Parâmetros de equipamentos registrados','Falhas e ações corretivas documentadas','Registro fotográfico realizado','Relatório técnico final preenchido','Apresentação técnica final realizada'];
const faults=[
 {id:'f1',title:'Motor não parte',prompt:'Ao pressionar START, o motor não entra em funcionamento. A sinalização de alimentação está ativa. Investigue sem trocar componentes por tentativa.',hints:['Verifique primeiro a alimentação do comando e o circuito de permissivos.','Meça a tensão na bobina do contator ou na entrada de comando do acionamento.','Compare o resultado com o diagrama antes de concluir.']},
 {id:'f2',title:'Relé térmico desarma',prompt:'O motor parte, funciona por alguns segundos e o relé de sobrecarga atua. Determine se a causa está no ajuste, na carga ou na alimentação.',hints:['Compare corrente medida com a corrente nominal de placa.','Verifique desequilíbrio / falta de fase e condição mecânica da carga.','Confirme o ajuste do relé térmico.']},
 {id:'f3',title:'Sentido de rotação incorreto',prompt:'O motor funciona normalmente, porém gira no sentido oposto ao requerido pelo processo. Proponha correção segura e registre o procedimento.',hints:['Confirme o sentido requerido e a sequência de fases.','Desenergize antes de qualquer intervenção.','Em motor trifásico, a inversão de duas fases altera o sentido de rotação.']},
 {id:'f4',title:'Inversor em falha',prompt:'O inversor recebe alimentação, mas indica falha e não libera o motor. Analise parâmetros, permissivos e dados de placa.',hints:['Registre o código de falha antes de resetar.','Consulte o manual e confronte os parâmetros básicos do motor.','Verifique permissivos e circuito de segurança.']},
 {id:'f5',title:'Contator vibra / não sela',prompt:'O contator aciona de forma instável e não permanece energizado. Investigue tensão da bobina, contatos auxiliares e circuito de selo.',hints:['Meça tensão em A1-A2 durante a tentativa de partida.','Confira o contato auxiliar de selo no diagrama.','Inspecione aperto e continuidade do circuito de comando.']}
];
const emptyState=()=>({project:{team:'',class:'',asset:'',date:new Date().toISOString().slice(0,10),members:''},safety:{checks:{},notes:''},motor:{power:'',voltage:'',current:'',frequency:'60',rpm:'',pf:'',eff:'',connection:'',ip:''},components:{driveType:'',protection:'',switching:'',overload:'',control:'',cables:''},assembly:{checks:{},notes:''},measurements:{voltage:'',current:'',frequency:'',rotation:''},faults:{scenario:'',hypothesis:'',test:'',result:'',conclusion:'',evaluated:false},commission:{checks:{}},evidence:{checks:{},summary:'',learning:''}});
let state=load();
function load(){try{return {...emptyState(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return emptyState()}}
function setPath(obj,path,val){const p=path.split('.');let cur=obj;while(p.length>1){const k=p.shift();cur[k]??={};cur=cur[k]}cur[p[0]]=val}
function getPath(obj,path){return path.split('.').reduce((a,k)=>a?.[k],obj)}
function pctChecks(checks,items){const done=items.filter((_,i)=>checks?.[i]).length;return Math.round(done/items.length*100)}
function filled(vals){return vals.filter(v=>String(v??'').trim()!=='').length}
function bindInputs(){document.querySelectorAll('[data-bind]').forEach(el=>{const p=el.dataset.bind;el.value=getPath(state,p)??'';el.addEventListener('input',()=>{setPath(state,p,el.dataset.number!==undefined?(el.value===''?'':Number(el.value)):el.value);if(p==='faults.hypothesis'||p==='faults.test'||p==='faults.result'||p==='faults.conclusion')state.faults.evaluated=false;refresh()})})}
function renderCheckList(containerId,group,items){const c=document.getElementById(containerId);c.innerHTML='';items.forEach((txt,i)=>{const lab=document.createElement('label');lab.className='check-item';lab.innerHTML=`<input type="checkbox" ${state[group].checks?.[i]?'checked':''}><span>${txt}</span>`;lab.querySelector('input').addEventListener('change',e=>{state[group].checks[i]=e.target.checked;refresh()});c.appendChild(lab)})}
function initFaults(){const s=document.getElementById('faultScenario');faults.forEach(f=>{const o=document.createElement('option');o.value=f.id;o.textContent=f.title;s.appendChild(o)});s.value=state.faults.scenario||'';s.addEventListener('change',()=>{state.faults.scenario=s.value;state.faults.evaluated=false;refresh()});document.getElementById('btnRandomFault').onclick=()=>{const f=faults[Math.floor(Math.random()*faults.length)];state.faults.scenario=f.id;s.value=f.id;state.faults.evaluated=false;refresh()};document.getElementById('btnEvaluateFault').onclick=()=>{state.faults.evaluated=true;refresh()}}
function initTabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')})}
function analyzeMotor(){const m=state.motor;const a=[];if(m.power&&m.voltage&&m.current){const apparent=Math.sqrt(3)*m.voltage*m.current/1000;a.push(`Potência aparente estimada pela placa: ${apparent.toFixed(2)} kVA.`);if(m.pf)a.push(`Potência elétrica ativa aproximada: ${(apparent*m.pf).toFixed(2)} kW.`)}if(m.rpm&&m.frequency){const poles=[2,4,6,8,10,12];const sync=poles.map(p=>({p,ns:120*m.frequency/p,d:Math.abs(120*m.frequency/p-m.rpm)})).sort((a,b)=>a.d-b.d)[0];if(sync){const slip=(sync.ns-m.rpm)/sync.ns*100;a.push(`Estimativa didática: motor próximo de ${sync.p} polos, velocidade síncrona ${sync.ns.toFixed(0)} rpm, escorregamento ≈ ${slip.toFixed(1)}%.`)}}return a.length?a.join(' '):'Preencha tensão, corrente e demais dados para gerar a análise automática.'}
function validateComponents(){const c=state.components,issues=[];if(!c.driveType)issues.push('Selecione o tipo de acionamento.');if(!c.protection)issues.push('Informe a proteção principal.');if(['Partida direta','Partida direta com reversão','Estrela-triângulo'].includes(c.driveType)&&!c.switching)issues.push('Acionamento eletromecânico normalmente requer dispositivo de manobra identificado.');if(c.driveType==='Estrela-triângulo'&&!/contator/i.test(c.switching))issues.push('Confira se a solução prevê os contatores necessários à comutação estrela-triângulo.');if(c.driveType==='Soft-starter'&&!/soft/i.test(`${c.switching} ${c.control}`))issues.push('Registre explicitamente a soft-starter e seus requisitos de comando/proteção.');if(c.driveType==='Inversor de frequência'&&!/inversor|cfw|vfd/i.test(`${c.switching} ${c.control}`))issues.push('Registre explicitamente o inversor de frequência e seus requisitos de comando/proteção.');return issues}
function measurements(){const m=state.measurements,n=state.motor;const f=(v,nom)=>v&&nom?((v-nom)/nom*100):null;return{vd:f(m.voltage,n.voltage),cd:f(m.current,n.current),fd:f(m.frequency,n.frequency)}}
function faultFeedback(){const f=faults.find(x=>x.id===state.faults.scenario);if(!f)return 'Selecione ou sorteie uma falha.';if(!state.faults.evaluated)return `Sintoma: ${f.prompt}`;const q=[state.faults.hypothesis,state.faults.test,state.faults.result,state.faults.conclusion].map(x=>String(x||'').trim());if(q.some(x=>!x))return 'O diagnóstico está incompleto. Registre hipótese, teste, resultado e conclusão antes de encerrar.';const words=(q.join(' ').match(/\b(tens[aã]o|corrente|medir|medição|diagrama|continuidade|bobina|fase|parâmetro|manual|segurança|desenerg)/gi)||[]).length;if(words>=3)return `Raciocínio técnico registrado. Antes de validar, confronte a conclusão com o diagrama, as medições e o procedimento seguro. Pista final: ${f.hints[2]}`;return `A descrição ainda está genérica. Acrescente medições objetivas e a relação entre sintoma, hipótese e evidência. Pista: ${f.hints[1]}`}
function stagePercents(){const motorVals=[state.motor.power,state.motor.voltage,state.motor.current,state.motor.frequency,state.motor.rpm,state.motor.connection];const compVals=Object.values(state.components);const measVals=[state.measurements.voltage,state.measurements.current,state.measurements.frequency,state.measurements.rotation];const faultVals=[state.faults.scenario,state.faults.hypothesis,state.faults.test,state.faults.result,state.faults.conclusion];return[ pctChecks(state.safety.checks,safetyItems), Math.round(filled(motorVals)/motorVals.length*100), Math.round(filled(compVals)/compVals.length*100), pctChecks(state.assembly.checks,assemblyItems), Math.round(filled(measVals)/measVals.length*100), Math.round(filled(faultVals)/faultVals.length*100), pctChecks(state.commission.checks,commissionItems), Math.round((pctChecks(state.evidence.checks,evidenceItems)+(state.evidence.summary?100:0)+(state.evidence.learning?100:0))/3) ]}
function reportHTML(){const c=state.components,m=state.motor,me=state.measurements,p=stagePercents();const rel=p[6]===100;return `
<h3>1. Identificação</h3><table class="report-table"><tr><th>Equipe</th><td>${esc(state.project.team)}</td><th>Turma</th><td>${esc(state.project.class)}</td></tr><tr><th>Ativo</th><td>${esc(state.project.asset)}</td><th>Data</th><td>${esc(state.project.date)}</td></tr><tr><th>Integrantes</th><td colspan="3">${esc(state.project.members)}</td></tr></table>
<h3>2. Dados do motor</h3><table class="report-table"><tr><th>Potência</th><td>${m.power||'—'} kW</td><th>Tensão</th><td>${m.voltage||'—'} V</td></tr><tr><th>Corrente</th><td>${m.current||'—'} A</td><th>Frequência</th><td>${m.frequency||'—'} Hz</td></tr><tr><th>Rotação</th><td>${m.rpm||'—'} rpm</td><th>Ligação</th><td>${esc(m.connection)||'—'}</td></tr></table>
<h3>3. Acionamento e componentes</h3><table class="report-table"><tr><th>Tipo</th><td>${esc(c.driveType)||'—'}</td><th>Proteção</th><td>${esc(c.protection)||'—'}</td></tr><tr><th>Manobra</th><td>${esc(c.switching)||'—'}</td><th>Sobrecarga</th><td>${esc(c.overload)||'—'}</td></tr><tr><th>Comando</th><td>${esc(c.control)||'—'}</td><th>Condutores</th><td>${esc(c.cables)||'—'}</td></tr></table>
<h3>4. Segurança e montagem</h3><p><strong>Segurança:</strong> ${p[0]}% concluída. <strong>Montagem:</strong> ${p[3]}% concluída.</p><p>${esc(state.safety.notes)}</p><p>${esc(state.assembly.notes)}</p>
<h3>5. Medições</h3><table class="report-table"><tr><th>Tensão</th><td>${me.voltage||'—'} V</td><th>Corrente</th><td>${me.current||'—'} A</td></tr><tr><th>Frequência</th><td>${me.frequency||'—'} Hz</td><th>Rotação</th><td>${esc(me.rotation)||'—'}</td></tr></table>
<h3>6. Diagnóstico de falha</h3><p><strong>Cenário:</strong> ${esc(faults.find(x=>x.id===state.faults.scenario)?.title||'—')}</p><p><strong>Hipótese:</strong> ${esc(state.faults.hypothesis)}</p><p><strong>Teste:</strong> ${esc(state.faults.test)}</p><p><strong>Resultado:</strong> ${esc(state.faults.result)}</p><p><strong>Conclusão:</strong> ${esc(state.faults.conclusion)}</p>
<h3>7. Liberação</h3><p><strong>${rel?'SISTEMA APTO PARA OPERAÇÃO':'PENDÊNCIAS PARA LIBERAÇÃO'}</strong> — checklist final ${p[6]}% concluído.</p>
<h3>8. Produto e evidências</h3><p><strong>Resumo técnico:</strong> ${esc(state.evidence.summary)}</p><p><strong>Aprendizados da equipe:</strong> ${esc(state.evidence.learning)}</p>`}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function refresh(){const p=stagePercents(),avg=Math.round(p.reduce((a,b)=>a+b,0)/p.length);document.getElementById('progressBar').style.width=avg+'%';document.getElementById('progressText').textContent=`${avg}% concluído`;const gs=document.getElementById('generalStatus');gs.textContent=avg===100?'CONCLUÍDO':'EM ANDAMENTO';gs.className='status-pill '+(avg===100?'ok':'warn');document.getElementById('stageChips').innerHTML=['Segurança','Motor','Componentes','Montagem','Medições','Diagnóstico','Comissionamento','Evidências'].map((x,i)=>`<span class="chip ${p[i]===100?'done':''}">${x}: ${p[i]}%</span>`).join('');['safetyBadge','motorBadge','componentBadge','assemblyBadge','measurementBadge','faultBadge','commissionBadge','evidenceBadge'].forEach((id,i)=>document.getElementById(id).textContent=p[i]+'%');document.getElementById('motorAnalysis').textContent=analyzeMotor();const mm=measurements();document.getElementById('voltageDeviation').textContent=mm.vd==null?'—':`${mm.vd.toFixed(1)}%`;document.getElementById('currentDeviation').textContent=mm.cd==null?'—':`${mm.cd.toFixed(1)}%`;document.getElementById('freqDeviation').textContent=mm.fd==null?'—':`${mm.fd.toFixed(1)}%`;document.getElementById('rotationResult').textContent=state.measurements.rotation||'—';document.getElementById('measurementAnalysis').textContent=mm.vd==null?'Os desvios serão comparados com os dados nominais do motor.':`Desvio de tensão ${mm.vd.toFixed(1)}%; corrente ${mm.cd==null?'—':mm.cd.toFixed(1)+'%'}; frequência ${mm.fd==null?'—':mm.fd.toFixed(1)+'%'}. Avalie os resultados considerando projeto, placa, carga e procedimento de ensaio.`;const f=faults.find(x=>x.id===state.faults.scenario);document.getElementById('faultPrompt').textContent=f?f.prompt:'Selecione um cenário.';document.getElementById('faultFeedback').textContent=faultFeedback();const rel=p[6]===100,rs=document.getElementById('releaseStatus');rs.className='release '+(rel?'released':'blocked');rs.innerHTML=rel?'<strong>SISTEMA APTO PARA OPERAÇÃO</strong><span>Checklist final concluído. Registre as evidências e emita o relatório.</span>':'<strong>PENDÊNCIAS PARA LIBERAÇÃO</strong><span>Conclua os itens críticos para liberar o sistema.</span>';document.getElementById('reportContent').innerHTML=reportHTML();localStorage.setItem(KEY,JSON.stringify(state))}
function saveFile(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function init(){renderCheckList('safetyList','safety',safetyItems);renderCheckList('assemblyList','assembly',assemblyItems);renderCheckList('commissionList','commission',commissionItems);renderCheckList('evidenceList','evidence',evidenceItems);bindInputs();initTabs();initFaults();document.getElementById('btnValidateComponents').onclick=()=>{const issues=validateComponents(),el=document.getElementById('componentAnalysis');el.className='callout '+(issues.length?'bad':'ok');el.innerHTML=issues.length?'<strong>Verifique:</strong> '+issues.join(' '):'<strong>Coerência básica atendida.</strong> Confirme ainda dimensionamento, manuais e requisitos do projeto.'};document.getElementById('btnSave').onclick=()=>{localStorage.setItem(KEY,JSON.stringify(state));alert('Projeto salvo neste navegador.')};document.getElementById('btnExport').onclick=()=>saveFile(`comissionamento-${(state.project.team||'equipe').replace(/\s+/g,'-')}.json`,JSON.stringify(state,null,2));document.getElementById('fileImport').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);localStorage.setItem(KEY,JSON.stringify(state));location.reload()}catch{alert('Arquivo JSON inválido.')}};r.readAsText(f)});document.getElementById('btnReport').onclick=()=>{document.getElementById('report').scrollIntoView({behavior:'smooth'});setTimeout(()=>window.print(),350)};let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;const b=document.getElementById('btnInstall');b.hidden=false;b.onclick=async()=>{deferred.prompt();await deferred.userChoice;b.hidden=true}});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');refresh()}
init();
